apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: log-output-writer:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
        - name: log-output-response
          image: log-output-response:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
